name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test_build_publish:
    runs-on: ubuntu-latest
    # Make sure the branch reference is 'main' as you've specified 'main' above in the on.push.branches section
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.1'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm install

      - name: Create .env for tests
        run: |
          echo "AWS_ACCESS_KEY=\"$AWS_ACCESS_KEY\"" >> .env
          echo "AWS_SECRET_KEY=\"$AWS_SECRET_KEY\"" >> .env
          echo "AWS_REGION=\"$AWS_REGION\"" >> .env
          echo "AWS_LOCK_TABLE_NAME=\"$AWS_LOCK_TABLE_NAME\"" >> .env
          echo "AWS_STORAGE_TABLE_NAME=\"$AWS_STORAGE_TABLE_NAME\"" >> .env
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_LOCK_TABLE_NAME: ${{ secrets.AWS_LOCK_TABLE_NAME }}
          AWS_STORAGE_TABLE_NAME: ${{ secrets.AWS_STORAGE_TABLE_NAME }}
        shell: bash

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
